# Generated by Django 5.2 on 2025-04-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingoapp', '0002_alter_usercustom_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='phone',
            field=models.CharField(blank=True, default='N/A', max_length=15, null=True, unique=True),
        ),
    ]
