# Generated by Django 5.2 on 2025-04-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingoapp', '0003_alter_usercustom_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
