# Generated by Django 5.2 on 2025-04-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingoapp', '0004_usercustom_telegram_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
