# Generated by Django 5.2 on 2025-04-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingoapp', '0007_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='withdrawals',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
